[package]
name = "tauri-plugin-speu-mangadex"
version = "0.3.0"
authors = ["You"]
description = "The tauri plugin behind the Mangadex Part of special-eureka"
edition = "2024"
rust-version = "1.86"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]
links = "mangadex-desktop-api"

[build-dependencies]
mizuki-build.workspace = true

[dependencies]
tauri = { workspace = true }
serde.workspace = true
tokio.workspace = true
thiserror.workspace = true
reqwest.workspace = true
log.workspace = true
once_cell = "1"
serde_json.workspace = true
mangadex-api = { version = "3.4", default-features = false, features = [
	"rw-multi-thread",
	"serialize",
	"utils",
] }
mangadex-api-schema-rust = { version = "0.10", default-features = false, features = [
	"serialize",
] }
mangadex-api-types-rust = { version = "0.10", default-features = false, features = [
	"async-graphql",
] }
async-graphql.workspace = true
convert_case = "0.8"
tokio-stream = { version = "0", features = ["sync"] }
regex.workspace = true
bytes.workspace = true
async-stream = "0"
favicon-picker = "1.0.0"
tempfile = "3.10.1"
tokio-util = "0.7.11"
emdx = "0.1"
actix.workspace = true
eureka-mmanager-core = "0.1"
tauri-plugin-notification.workspace = true
tower = { workspace = true, features = ["limit", "buffer"] }
duration-string = { version = "0.5", features = ["serde"] }
impl-trait-for-tuples = "0.2"
dirs.workspace = true
enum-repr.workspace = true
enum-kinds.workspace = true
serde_repr.workspace = true
governor.workspace = true
futures-util.workspace = true
image.workspace = true
serde-xml-rs.workspace = true
csv.workspace = true
hotpath = { workspace = true, optional = true }
shrink_fit_wrapper.workspace = true

[dependencies.eureka-mmanager]
version = "0.4"
default-features = false

[dependencies.mangadex-api-input-types]
version = "0.6"
features = ["mangadex-api-resolver", "async-graphql"]

[dependencies.mizuki]
workspace = true

[dependencies.url]
workspace = true
features = ["serde"]

[dependencies.uuid]
workspace = true
features = ["serde", "v4"]

[dependencies.time]
workspace = true
features = ["serde-human-readable", "large-dates", "local-offset"]

[dependencies.tauri-plugin-store]
workspace = true

[features]
hotpath = ["dep:hotpath"]