# Move all package.json tasks here

[tasks.run]
workspace = false
command = "pnpm"
args = ["dev"]

[tasks.upx-release]
workspace = false
script_runner = "@duckscript"
script = { file = "./scripts/upx-release.ds" }

[tasks.clippy-fast]
workspace = false
command = "cargo"
args = [
	"clippy", 
	"--profile",
	"clippy-fast"
]

[tasks.clippy-fast-ci]
workspace = false
command = "cargo"
args = [
	"clippy", 
	"--profile",
	"clippy-fast",
	"--",
	"-D",
	"clippy::perf",
	"-D",
	"clippy::style"
]

[tasks.run-workspace-tests]
workspace = false
command = "cargo"
args = [
	"test", 
	"--workspace", 
	"--tests"
]

[tasks.fmt-rust]
command = "cargo"
args = [
	"fmt"
]

[tasks.fmt-js-svelte]
workspace = false
command = "pnpm"
args = ["format"]

[tasks.format]
workspace = false
dependencies = ["fmt-rust", "fmt-js-svelte"]

[tasks.check-svelte]
workspace = false
command = "pnpm"
args = ["check"]