[tasks.run]
workspace = false
command = "pnpm"
args = ["dev"]

[tasks.upx-release]
workspace = false
script_runner = "@duckscript"
script = { file = "./scripts/upx-release.ds" }

[tasks.clippy]
workspace = false
command = "cargo"
args = [
	"clippy", 
	"--profile",
	"clippy"
]