ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - svelte-preprocess

overrides:
  ajv@<8.18.0: '>=8.18.0'
  cookie@<0.7.0: '>=0.7.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  minimatch@<10.2.1: '>=10.2.1'
  svelte@<4.2.19: '>=4.2.19'
