ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - svelte-preprocess

overrides:
  cookie@<0.7.0: '>=0.7.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  svelte@<4.2.19: '>=4.2.19'
