/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedString } from './localized-string';
/**
 * 
 * @export
 * @interface AuthorAttributes
 */
export interface AuthorAttributes {
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    imageUrl?: string;
    /**
     * 
     * @type {LocalizedString}
     * @memberof AuthorAttributes
     */
    biography?: LocalizedString;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    pixiv?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    melonBook?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    fanBox?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    booth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    nicoVideo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    skeb?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    fantia?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    tumblr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    youtube?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    weibo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    naver?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    website?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AuthorAttributes
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorAttributes
     */
    updatedAt?: string;
}
