/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChapterAttributes
 */
export interface ChapterAttributes {
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    volume?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    chapter?: string | null;
    /**
     * Count of readable images for this chapter
     * @type {number}
     * @memberof ChapterAttributes
     */
    pages?: number;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    translatedLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    uploader?: string;
    /**
     * Denotes a chapter that links to an external source.
     * @type {string}
     * @memberof ChapterAttributes
     */
    externalUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChapterAttributes
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    publishAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterAttributes
     */
    readableAt?: string;
}
