/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedString } from './localized-string';
import { Tag } from './tag';
/**
 * 
 * @export
 * @interface MangaAttributes
 */
export interface MangaAttributes {
    /**
     * 
     * @type {LocalizedString}
     * @memberof MangaAttributes
     */
    title?: LocalizedString;
    /**
     * 
     * @type {Array<LocalizedString>}
     * @memberof MangaAttributes
     */
    altTitles?: Array<LocalizedString>;
    /**
     * 
     * @type {LocalizedString}
     * @memberof MangaAttributes
     */
    description?: LocalizedString;
    /**
     * 
     * @type {boolean}
     * @memberof MangaAttributes
     */
    isLocked?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MangaAttributes
     */
    links?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    originalLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    lastVolume?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    lastChapter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    publicationDemographic?: MangaAttributesPublicationDemographicEnum;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    status?: MangaAttributesStatusEnum;
    /**
     * Year of release
     * @type {number}
     * @memberof MangaAttributes
     */
    year?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    contentRating?: MangaAttributesContentRatingEnum;
    /**
     * 
     * @type {boolean}
     * @memberof MangaAttributes
     */
    chapterNumbersResetOnNewVolume?: boolean;
    /**
     * 
     * @type {Array}
     * @memberof MangaAttributes
     */
    availableTranslatedLanguages?: Array;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    latestUploadedChapter?: string;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof MangaAttributes
     */
    tags?: Array<Tag>;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    state?: MangaAttributesStateEnum;
    /**
     * 
     * @type {number}
     * @memberof MangaAttributes
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MangaAttributes
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum MangaAttributesPublicationDemographicEnum {
    Shounen = 'shounen',
    Shoujo = 'shoujo',
    Josei = 'josei',
    Seinen = 'seinen'
}
/**
    * @export
    * @enum {string}
    */
export enum MangaAttributesStatusEnum {
    Completed = 'completed',
    Ongoing = 'ongoing',
    Cancelled = 'cancelled',
    Hiatus = 'hiatus'
}
/**
    * @export
    * @enum {string}
    */
export enum MangaAttributesContentRatingEnum {
    Safe = 'safe',
    Suggestive = 'suggestive',
    Erotica = 'erotica',
    Pornographic = 'pornographic'
}
/**
    * @export
    * @enum {string}
    */
export enum MangaAttributesStateEnum {
    Draft = 'draft',
    Submitted = 'submitted',
    Published = 'published',
    Rejected = 'rejected'
}

