/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Order1
 */
export interface Order1 {
    /**
     * 
     * @type {string}
     * @memberof Order1
     */
    name?: Order1NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Order1
     */
    createdAt?: Order1CreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof Order1
     */
    updatedAt?: Order1UpdatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof Order1
     */
    followedCount?: Order1FollowedCountEnum;
    /**
     * 
     * @type {string}
     * @memberof Order1
     */
    relevance?: Order1RelevanceEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Order1NameEnum {
    Asc = 'asc',
    Desc = 'desc'
}
/**
    * @export
    * @enum {string}
    */
export enum Order1CreatedAtEnum {
    Asc = 'asc',
    Desc = 'desc'
}
/**
    * @export
    * @enum {string}
    */
export enum Order1UpdatedAtEnum {
    Asc = 'asc',
    Desc = 'desc'
}
/**
    * @export
    * @enum {string}
    */
export enum Order1FollowedCountEnum {
    Asc = 'asc',
    Desc = 'desc'
}
/**
    * @export
    * @enum {string}
    */
export enum Order1RelevanceEnum {
    Asc = 'asc',
    Desc = 'desc'
}

