/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Relationship
 */
export interface Relationship {
    /**
     * 
     * @type {string}
     * @memberof Relationship
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Relationship
     */
    type?: string;
    /**
     * Related Manga type, only present if you are on a Manga entity and a Manga relationship
     * @type {string}
     * @memberof Relationship
     */
    related?: RelationshipRelatedEnum;
    /**
     * If Reference Expansion is applied, contains objects attributes
     * @type {any}
     * @memberof Relationship
     */
    attributes?: any | null;
}

/**
    * @export
    * @enum {string}
    */
export enum RelationshipRelatedEnum {
    Monochrome = 'monochrome',
    MainStory = 'main_story',
    AdaptedFrom = 'adapted_from',
    BasedOn = 'based_on',
    Prequel = 'prequel',
    SideStory = 'side_story',
    Doujinshi = 'doujinshi',
    SameFranchise = 'same_franchise',
    SharedUniverse = 'shared_universe',
    Sequel = 'sequel',
    SpinOff = 'spin_off',
    AlternateStory = 'alternate_story',
    AlternateVersion = 'alternate_version',
    Preserialization = 'preserialization',
    Colored = 'colored',
    Serialization = 'serialization'
}

