/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately.
 *
 * OpenAPI spec version: 5.7.5
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedString } from './localized-string';
/**
 * 
 * @export
 * @interface ScanlationGroupAttributes
 */
export interface ScanlationGroupAttributes {
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    name?: string;
    /**
     * 
     * @type {Array<LocalizedString>}
     * @memberof ScanlationGroupAttributes
     */
    altNames?: Array<LocalizedString>;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    ircServer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    ircChannel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    discord?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    mangaUpdates?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScanlationGroupAttributes
     */
    focusedLanguage?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScanlationGroupAttributes
     */
    locked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScanlationGroupAttributes
     */
    official?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScanlationGroupAttributes
     */
    inactive?: boolean;
    /**
     * Should respected ISO 8601 duration specification: https://en.wikipedia.org/wiki/ISO_8601#Durations
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    publishDelay?: string;
    /**
     * 
     * @type {number}
     * @memberof ScanlationGroupAttributes
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ScanlationGroupAttributes
     */
    updatedAt?: string;
}
