name: build-app-with-experimental-app-image
on:
    workflow_dispatch:
permissions:
    contents: write

jobs:
    tauri-build-experimental:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v5
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
            - name: install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            - name: install tauri-cli experimental app image
              run: cargo install tauri-cli --git https://github.com/tauri-apps/tauri.git --branch feat/truly-portable-appimage
            - name: install app dependencies
              run: pnpm install
            - name: build the actual app with tauri action
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PASSWORD }}
              with:
                  tagName: v__VERSION__.2
                  releaseName: "Special Eureka v__VERSION__ app-image experimental 2"
                  releaseBody: "An experimental app image release using the [tauri/feat/truly-portable-app-image](https://github.com/tauri-apps/tauri/pull/12491).\n Unlike the previous one, this uses `ubuntu-latest` instead."
                  releaseDraft: true
                  prerelease: true
                  tauriScript: cargo tauri

