name: "Javascript lint and tests"
permissions:
  contents: read
on:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup vite plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: install deps
        run: vp install
      - name: svelte checkes
        run: vp fmt --check ./src
  check-svelte:
    needs: check-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup vite plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: install deps
        run: pnpm install
      - name: svelte checkes
        run: vp run check
