name: "rust lint and tests"
permissions:
  contents: read
on:
  pull_request:
    paths:
      - "src-tauri/**"
      - "crates/**"
      - "Cargo.lock"
      - "Cargo.toml"

jobs:
  check-fmt:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: run Rust format
        run: cargo fmt --check
  run-clippy:
    needs: check-fmt
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    # Run this on all platform
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install cargo-make
        run: cargo install --force cargo-make
      - name: make build dir
        run: mkdir build
      - name: install mold linker
        uses: rui314/setup-mold@v1
        if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'
        with:
          make-default: false
      - name: install dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: change project cargo config
        if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'
        run: mv .cargo/build.config.toml .cargo/config.toml
      - name: Run clippy fast
        run: cargo make clippy-fast-ci
  run-tests:
    needs: run-clippy
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    # run this on all major platforms
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      # Mold is not supported on windows
      - name: install mold linker
        if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'
        uses: rui314/setup-mold@v1
        with:
          make-default: false
      # Switch to mold for faster compile times
      - name: change project cargo config
        if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'
        run: mv .cargo/build.config.toml .cargo/config.toml
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install cargo-make
        run: cargo install --force cargo-make
      # NOTE: This might not be required but i will keep this one here just in case :)
      - name: make build dir
        run: mkdir build
      - name: Run tests
        run: cargo make run-workspace-tests
