name : "vite test builds and cargo checks"
on :
    push
env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
    vite-build-test:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false
            - name: install packages 
              run : pnpm install
            - name : Run Vite builds
              run : pnpm vite:build
    cargo-checks:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.platform }}
        needs : vite-build-test
        steps: 
            - uses: actions/checkout@v4
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
            - name : Clippy checks
              run: |
                  cargo clippy --manifest-path=./src-tauri/Cargo.toml
